---
- name: Allow access to dump dir
  file:
    path: '{{ backup_dir }}'
    mode: 0777
  become: True

- name: Trust connection from localhost
  replace:
    path: /etc/postgresql/{{ postgres_version }}/main/pg_hba.conf
    regexp: 'host\s+all\s+all\s+127.0.0.1/32\s+md5'
    replace: 'host    all             all             127.0.0.1/32            trust'
  become: true
  when: use_docker is not defined

- name: Restart postgres
  service:
    name: postgresql
    state: restarted
  become: true
  when: use_docker is not defined

# Dump the database content (you will be prompted several time for the password above)

- name: Dump the database from host
  command: 'pg_dumpall --host=127.0.0.1 --file=pg_dumpall_{{ data_src }}.sql'
  args:
    chdir: '{{ backup_dir }}'
  become_user: postgres
  become: true
  when: use_docker is not defined

- name: Dump the database from docker
  shell: docker exec db4{{ project_name }} pg_dumpall -U postgres  --host=127.0.0.1 > pg_dumpall_{{ data_src }}.sql
  args:
    chdir: '{{ backup_dir }}'
  become: True
  when: use_docker is defined and use_docker == True
