---
- name: Copy custom geonode files to host
  copy:
    src: '{{ playbook_dir }}/geonode-project/{{ org }}/{{ project_dir }}/{{ item }}'
    dest: ~/geonode/geonode/{{ item }}
  with_items:
    - templates/
    # - guide/

- name: Copy custom static files
  copy:
    src: '{{ playbook_dir }}/geonode-project/{{ org }}/{{ project_dir }}/static/'
    dest: '{{ statics_dir }}/static/'
    # dest: '{{ statics_dir }}/static/{{ org }}-{{ project_dir }}/'
  become: True

- name: Set page title
  replace:
    path: ~/geonode/geonode/templates/site_base.html
    regexp: INSERT_PROJECT_HERE
    replace: '{{ project }}'

- debug:
    msg: 'TODO: Add guide links to About in top nav menu'

- name: Point to site index
  replace:
    path: ~/geonode/geonode/urls.py
    regexp: "template_name='index.html'"
    replace: "template_name='site_index.html'"

# - name: Add guide to URLs
#   lineinfile:
#     path: ~/geonode/geonode/urls.py
#     insertbefore: '# Layer views'
#     line: "(r'^guide/', include('geonode.guide.urls')), # Guide views"
#
- name: Copy custom geonode files to Django container
  command: docker cp {{ item }} django4{{ project_name }}:/usr/src/app/geonode/{{ item }}
  args:
    chdir: ~/geonode/geonode
  with_items:
    - urls.py
    - templates/.
