---
- name: Set public port for http
  set_fact:
    public_port: 80
  when: public_protocol == 'http'

- name: Set public port for https
  set_fact:
    public_port: 443
  when: public_protocol == 'https'

- name: Git Geonode
  git:
    repo: https://github.com/GeoNode/geonode
    dest: ~/geonode
    force: True

- name: Set project name for docker
  replace:
    path: ~/geonode/.env
    regexp: ^\s*COMPOSE_PROJECT_NAME\s*=.*$
    replace: COMPOSE_PROJECT_NAME={{ project_name }}

- name: Create folders for docker volumes
  file:
    name: '{{ item }}'
    state: directory
  with_items:
    - '{{ statics_dir }}'
    - '{{ log_dir }}/nginx'
  become: True
#
- name: Create project directory
  file:
    path: ~/{{ project_dir }}
    state: directory

- name: Copy tasks - patch for Geonode PR 4403
  copy:
    src: tasks.py
    dest: ~/geonode/tasks.py

# https://github.com/GeoNode/geonode/pull/4427
- debug:
    msg: "Delete this and the next 3 tasks when Geonode PR 4427 is merged"

# Remove extra parameter for TemplateResponse
- name: GN PR 4427 - Patch 1/2 for Geonode issue 4352
  replace:
    path: ~/geonode/geonode/base/admin.py
    regexp: context,
    replace: context)

- name: GN PR 4427 -Patch 2/2 for Geonode issue 4352
  lineinfile:
    path: ~/geonode/geonode/base/admin.py
    regexp: current_app=self.admin_site.name\)
    state: absent

- name: GN PR 4427 - Patch for TemplateSyntaxError at /en/admin/base/backup/
  lineinfile:
    path: ~/geonode/geonode/templates/admin/backups/confirm_cancel.html
    insertafter: "{{ '{%' }} extends \"admin/base_site.html\" {{ '%}' }}"
    line: "{{ '{%' }} load i18n {{ '%}' }}"

- name: Set gsdata dir for backup
  replace:
    path: ~/geonode/geonode/base/management/commands/settings.ini
    regexp: ^\s*datadir\s*=.*$
    replace: datadir = /geoserver_data/data

- name: Template docker-compose override files
  template:
    src: 'docker-compose.override.{{ item }}.yml.j2'
    dest: ~/{{ project_dir }}/docker-compose.override.{{ item }}.yml
  with_items:
    - hostname
    - volumes
    - django-env

- name: Link geoserver log to logs directory
  file:
    src: '{{ gsdata }}/logs/'
    dest: '{{ log_dir }}/geoserver'
    state: link
    force: True
    follow: False
  become: True

- name: Wait for Docker daemon to start
  pause:
    seconds: 90

- name: Launch the stack asynchronously
  shell: >
    docker-compose
    -f docker-compose.yml
    -f ~/{{ project_dir }}/docker-compose.override.hostname.yml
    -f ~/{{ project_dir }}/docker-compose.override.volumes.yml
    -f ~/{{ project_dir }}/docker-compose.override.django-env.yml
    up --build
  async: 600
  poll: 0
  args:
    chdir: ~/geonode

- name: Wait up to 5 minutes for django container to start
  shell: docker ps | grep -q 'Up.*django4{{ project_name }}'
  retries: 60
  delay: 5
  register: result
  until: result is succeeded

- name: Copy geonode to containers
  command: docker cp . {{ item }}4{{ project_name }}:/usr/src/app
  with_items:
    - django
    - celery
  args:
    chdir: ~/geonode
