---
# Install docker per  http://docs.geonode.org/en/master/tutorials/install_and_admin/running_docker/setup_docker.html

# Commented because it always comes up OK on a fresh-baked server
- name: Uninstall docker
  apt:
    name: '{{ packages }}'
    state: absent
  vars:
    packages:
      - docker
      - docker-engine
      - docker.io
  become: true

- name: Install packages to allow apt to use a repository over HTTPS
  apt:
    name: '{{ packages }}'
    update_cache: yes
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
  become: true

- name: Add Docker’s official GPG key
  # curl -fsSL  | sudo apt-key add -
  # sudo apt-key fingerprint 0EBFCD88
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    # id: 0EBFCD88
  become: true

- name: Set up the stable repository to install docker
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
  become: true

- name: Install docker CE
  apt:
    name: '{{ packages }}'
    update_cache: yes
  vars:
    packages:
      - docker-ce
  become: true

# Install docker-compose per  http://docs.geonode.org/en/master/tutorials/install_and_admin/running_docker/setup_docker_compose.html#install-docker-compose-on-ubuntu
- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_version }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}
    dest: /usr/local/bin/docker-compose
    mode: 0755
  become: true

- name: Allow user to run docker
  user:
    name: '{{ ansible_user_id }}'
    groups: docker
  become: true

# Commented because last step failed with: fatal error: ffi.h: No such file or directory
# - name: Install pip
#   apt:
#     name: python3-pip
#     update_cache: True
#   become: True
#
# - name: Install python docker for Ansible
#   pip:
#     name:
#       - docker-py
#       - docker-compose # This failed with fatal error: ffi.h: No such file or directory
#   become: True
