---

- include_tasks: set_hostname.yml

- include_tasks: set_timezone.yml

- include_tasks: mount_disk.yml

- name: Check tmp folder
  stat:
    path: /tmp
  register: tmp_check

- include_tasks: mv_tmp_to_big_disk.yml
  when: "tmp_check.stat.islnk is not defined or (tmp_check.stat.islnk is defined and tmp_check.stat.islnk == False) and 'small_sysdisk' in group_names"

- include_tasks: install_docker.yml

- name: Check docker folder
  stat:
    path: /var/lib/docker
  register: docker_check

- include_tasks: mv_docker_to_big_disk.yml
  when: "docker_check.stat.islnk is not defined or (docker_check.stat.islnk is defined and docker_check.stat.islnk == False)"

- name: Create data dirs
  file:
    path: '{{ item }}'
    state: directory
  become: true
  with_items:
    - '{{ gsdata }}'
    - '{{ postgres_data_directory }}'

# - include_tasks: install_python2.7.yml

# - include_tasks: install_gn_packages.yml

# Let's proceed without Java for now. Package broken 17 April 2019 still not updated 26 April.
# - include_tasks: install_java.yml
# - include_tasks: install_java_workaround.yml

# - name: Rename project
#   command: mv project_name {{ project_dir }}
#   args:
#     creates: '{{ project_dir }}'
#   delegate_to: localhost

# - include_tasks: install_python_support.yml

# - name: Make share folder writeable
#   file:
#     path: /usr/local/share
#     mode: 777
#   become: true
